// Course content. Speaking-first: every item is a word or a ready-to-use phrase,
// with an example sentence to shadow. Pinyin shows dictionary tones, except 不 and 一,
// which are written as said (bú shì, yí ge), as textbooks do. The app works out the
// 3–3 changes (你好 → ní hǎo) itself and shows them under the pinyin.
//
// Item fields: id, zh (simplified), py (pinyin), en, ex: [zh, py, en], note?, lit? (word by word)

export const UNITS = [
  {
    id: 'u1', title: 'Hello & goodbye', emoji: '👋',
    items: [
      { id: 'nihao', zh: '你好', py: 'nǐ hǎo', en: 'hello', ex: ['你好，我是安娜。', 'Nǐ hǎo, wǒ shì Ānnà.', 'Hello, I\'m Anna.'], note: 'Two 3rd tones in a row: the first is said like a 2nd tone → ní hǎo. The "Tone change" line under the pinyin shows wherever this happens.', lit: 'you good' },
      { id: 'ninhao', zh: '您好', py: 'nín hǎo', en: 'hello (polite)', ex: ['老师，您好！', 'Lǎoshī, nín hǎo!', 'Hello, teacher!'], lit: 'you (polite) good' },
      { id: 'zaijian', zh: '再见', py: 'zài jiàn', en: 'goodbye', ex: ['明天见，再见！', 'Míngtiān jiàn, zàijiàn!', 'See you tomorrow, bye!'], lit: 'again see' },
      { id: 'xiexie', zh: '谢谢', py: 'xièxie', en: 'thank you', ex: ['谢谢你！', 'Xièxie nǐ!', 'Thank you!'] },
      { id: 'bukeqi', zh: '不客气', py: 'bú kèqi', en: 'you\'re welcome', ex: ['谢谢！——不客气。', 'Xièxie! — Bú kèqi.', 'Thanks! — You\'re welcome.'], note: '不 is normally bù, but becomes bú before a 4th tone.', lit: 'don\'t be so polite' },
      { id: 'duibuqi', zh: '对不起', py: 'duìbuqǐ', en: 'sorry', ex: ['对不起，我来晚了。', 'Duìbuqǐ, wǒ lái wǎn le.', 'Sorry, I\'m late.'], lit: 'can\'t face (you)' },
      { id: 'meiguanxi', zh: '没关系', py: 'méi guānxi', en: 'it\'s okay / no problem', ex: ['对不起！——没关系。', 'Duìbuqǐ! — Méi guānxi.', 'Sorry! — It\'s okay.'], lit: 'there\'s no connection' },
      { id: 'zaoshanghao', zh: '早上好', py: 'zǎoshang hǎo', en: 'good morning', ex: ['妈妈，早上好！', 'Māma, zǎoshang hǎo!', 'Good morning, Mom!'], lit: 'morning good' },
      { id: 'wanan', zh: '晚安', py: 'wǎn\'ān', en: 'good night', ex: ['我睡觉了，晚安！', 'Wǒ shuìjiào le, wǎn\'ān!', 'I\'m going to sleep, good night!'], lit: 'evening peace' },
      { id: 'mingtianjian', zh: '明天见', py: 'míngtiān jiàn', en: 'see you tomorrow', ex: ['好的，明天见！', 'Hǎo de, míngtiān jiàn!', 'Okay, see you tomorrow!'], lit: 'tomorrow see' },
    ],
  },
  {
    id: 'u2', title: 'Me & you', emoji: '🙋',
    items: [
      { id: 'wo', zh: '我', py: 'wǒ', en: 'I / me', ex: ['我很好。', 'Wǒ hěn hǎo.', 'I\'m well.'] },
      { id: 'ni', zh: '你', py: 'nǐ', en: 'you', ex: ['你呢？', 'Nǐ ne?', 'And you?'] },
      { id: 'ta', zh: '他 / 她', py: 'tā', en: 'he / she', ex: ['她是我朋友。', 'Tā shì wǒ péngyou.', 'She is my friend.'], note: 'Both sound exactly the same: tā.' },
      { id: 'women', zh: '我们', py: 'wǒmen', en: 'we / us', ex: ['我们走吧。', 'Wǒmen zǒu ba.', 'Let\'s go.'] },
      { id: 'shi', zh: '是', py: 'shì', en: 'to be (am / is / are)', ex: ['我是学生。', 'Wǒ shì xuésheng.', 'I am a student.'], note: 'Use 是 to link two nouns ("I am a student"), not with adjectives: "I\'m busy" is 我很忙, not 我是忙.' },
      { id: 'bushi', zh: '不是', py: 'bú shì', en: 'am not / is not', ex: ['我不是老师。', 'Wǒ bú shì lǎoshī.', 'I\'m not a teacher.'], lit: 'not be' },
      { id: 'jiao', zh: '我叫…', py: 'wǒ jiào…', en: 'my name is…', ex: ['我叫大卫。', 'Wǒ jiào Dàwèi.', 'My name is David.'], lit: 'I am called…' },
      { id: 'jiaoshenme', zh: '你叫什么名字？', py: 'nǐ jiào shénme míngzi?', en: 'what\'s your name?', ex: ['你好，你叫什么名字？', 'Nǐ hǎo, nǐ jiào shénme míngzi?', 'Hi, what\'s your name?'], lit: 'you are called what name?' },
      { id: 'henhao', zh: '很好', py: 'hěn hǎo', en: 'very good / very well', ex: ['我很好，谢谢。', 'Wǒ hěn hǎo, xièxie.', 'I\'m well, thanks.'], note: 'Before an adjective, 很 is often just a link, not "very": 我很好 simply means "I\'m well". Stress 很 when you do mean "very".' },
      { id: 'nihaoma', zh: '你好吗？', py: 'nǐ hǎo ma?', en: 'how are you?', ex: ['你好吗？——我很好。', 'Nǐ hǎo ma? — Wǒ hěn hǎo.', 'How are you? — I\'m well.'], note: '吗 (ma) at the end turns a statement into a yes/no question. 你好吗 is common in textbooks, but friends usually just say 你好.', lit: 'you good?' },
      { id: 'ne', zh: '你呢？', py: 'nǐ ne?', en: 'and you?', ex: ['我很好，你呢？', 'Wǒ hěn hǎo, nǐ ne?', 'I\'m well, and you?'] },
      { id: 'renshini', zh: '很高兴认识你', py: 'hěn gāoxìng rènshi nǐ', en: 'nice to meet you', ex: ['我叫安娜，很高兴认识你。', 'Wǒ jiào Ānnà, hěn gāoxìng rènshi nǐ.', 'I\'m Anna, nice to meet you.'], lit: 'very glad to know you' },
    ],
  },
  {
    id: 'u3', title: 'Numbers 1–10', emoji: '🔢',
    items: [
      { id: 'yi', zh: '一', py: 'yī', en: 'one', ex: ['一个人', 'yí ge rén', 'one person'], note: '一 changes tone: yí before a 4th tone, yì before tones 1–3.' },
      { id: 'er', zh: '二', py: 'èr', en: 'two', ex: ['二月', 'èryuè', 'February'] },
      { id: 'san', zh: '三', py: 'sān', en: 'three', ex: ['三个苹果', 'sān ge píngguǒ', 'three apples'], note: '个 (ge) is a measure word: Chinese puts one between a number and a noun, as in 三个苹果 (never 三苹果). 个 is the all-purpose one.' },
      { id: 'si', zh: '四', py: 'sì', en: 'four', ex: ['四点', 'sì diǎn', 'four o\'clock'] },
      { id: 'wu', zh: '五', py: 'wǔ', en: 'five', ex: ['五块钱', 'wǔ kuài qián', 'five yuan'] },
      { id: 'liu', zh: '六', py: 'liù', en: 'six', ex: ['六个人', 'liù ge rén', 'six people'] },
      { id: 'qi', zh: '七', py: 'qī', en: 'seven', ex: ['七天', 'qī tiān', 'seven days'] },
      { id: 'ba', zh: '八', py: 'bā', en: 'eight', ex: ['八点', 'bā diǎn', 'eight o\'clock'] },
      { id: 'jiu', zh: '九', py: 'jiǔ', en: 'nine', ex: ['九月', 'jiǔyuè', 'September'] },
      { id: 'shi2', zh: '十', py: 'shí', en: 'ten', ex: ['十块', 'shí kuài', 'ten yuan'] },
      { id: 'liang', zh: '两', py: 'liǎng', en: 'two (of something)', ex: ['两个人', 'liǎng ge rén', 'two people'], note: 'Use 两, not 二, when counting things.' },
      { id: 'ling', zh: '零', py: 'líng', en: 'zero', ex: ['一零一', 'yāo líng yāo', '101 (as a room number)'], note: 'In phone and room numbers, 一 is often read yāo.' },
    ],
  },
  {
    id: 'u4', title: 'Yes, no & questions', emoji: '❓',
    items: [
      { id: 'dui', zh: '对', py: 'duì', en: 'right / correct', ex: ['对，我是美国人。', 'Duì, wǒ shì Měiguó rén.', 'Right, I\'m American.'], note: 'Chinese has no single word for "yes" or "no". Answer with the verb from the question: 是 / 不是, 有 / 没有, 要 / 不要. 对 means "that\'s right".' },
      { id: 'budui', zh: '不对', py: 'bú duì', en: 'not right / wrong', ex: ['不对，是八点。', 'Bú duì, shì bā diǎn.', 'No, it\'s eight o\'clock.'] },
      { id: 'hao', zh: '好', py: 'hǎo', en: 'good / okay', ex: ['好，我们走吧。', 'Hǎo, wǒmen zǒu ba.', 'Okay, let\'s go.'] },
      { id: 'haode', zh: '好的', py: 'hǎo de', en: 'okay / sure', ex: ['好的，没问题。', 'Hǎo de, méi wèntí.', 'Sure, no problem.'] },
      { id: 'meiwenti', zh: '没问题', py: 'méi wèntí', en: 'no problem', ex: ['明天？没问题！', 'Míngtiān? Méi wèntí!', 'Tomorrow? No problem!'] },
      { id: 'shenme', zh: '什么', py: 'shénme', en: 'what', ex: ['这是什么？', 'Zhè shì shénme?', 'What is this?'], note: 'Questions with 什么, 谁 or 哪里 don\'t take 吗. The question word goes where the answer would: 这是什么？ → 这是茶。' },
      { id: 'shei', zh: '谁', py: 'shéi', en: 'who', ex: ['他是谁？', 'Tā shì shéi?', 'Who is he?'], note: 'Also said shuí.' },
      { id: 'nali', zh: '哪里', py: 'nǎlǐ', en: 'where', ex: ['洗手间在哪里？', 'Xǐshǒujiān zài nǎlǐ?', 'Where is the restroom?'], note: '哪里 nǎlǐ (where?) and 那里 nàlǐ (there) differ only in tone, and 哪里 is said nálǐ (two 3rd tones).', lit: 'which place' },
      { id: 'zenmeyang', zh: '怎么样', py: 'zěnmeyàng', en: 'how is it? / how about…?', ex: ['明天怎么样？', 'Míngtiān zěnmeyàng?', 'How about tomorrow?'] },
      { id: 'weishenme', zh: '为什么', py: 'wèishénme', en: 'why', ex: ['你为什么学中文？', 'Nǐ wèishénme xué Zhōngwén?', 'Why are you learning Chinese?'], lit: 'for what' },
      { id: 'duoshao', zh: '多少', py: 'duōshao', en: 'how many / how much', ex: ['多少钱？', 'Duōshao qián?', 'How much is it?'], note: '多少 asks about any amount. For small numbers, like the time or people in a family, use 几 jǐ: 几点？ 几口人？', lit: 'many-few' },
    ],
  },
  {
    id: 'u5', title: 'Survival phrases', emoji: '🆘',
    items: [
      { id: 'tingbudong', zh: '我听不懂', py: 'wǒ tīng bu dǒng', en: 'I don\'t understand (what I hear)', ex: ['对不起，我听不懂。', 'Duìbuqǐ, wǒ tīng bu dǒng.', 'Sorry, I don\'t understand.'], lit: 'I listen not understand' },
      { id: 'mandian', zh: '请说慢一点', py: 'qǐng shuō màn yìdiǎn', en: 'please speak a bit slower', ex: ['老师，请说慢一点。', 'Lǎoshī, qǐng shuō màn yìdiǎn.', 'Teacher, please speak a bit slower.'], lit: 'please speak slow a little' },
      { id: 'zaishuo', zh: '请再说一遍', py: 'qǐng zài shuō yí biàn', en: 'please say it again', ex: ['对不起，请再说一遍。', 'Duìbuqǐ, qǐng zài shuō yí biàn.', 'Sorry, please say it again.'], lit: 'please again say one time' },
      { id: 'zenmeshuo', zh: '…用中文怎么说？', py: '… yòng Zhōngwén zěnme shuō?', en: 'how do you say … in Chinese?', ex: ['"Apple" 用中文怎么说？', '"Apple" yòng Zhōngwén zěnme shuō?', 'How do you say "apple" in Chinese?'], lit: '… use Chinese how say?' },
      { id: 'shenmeyisi', zh: '…是什么意思？', py: '… shì shénme yìsi?', en: 'what does … mean?', ex: ['这个词是什么意思？', 'Zhège cí shì shénme yìsi?', 'What does this word mean?'], lit: '… is what meaning?' },
      { id: 'huishuo', zh: '我会说一点中文', py: 'wǒ huì shuō yìdiǎn Zhōngwén', en: 'I can speak a little Chinese', ex: ['我会说一点中文，不多。', 'Wǒ huì shuō yìdiǎn Zhōngwén, bù duō.', 'I speak a little Chinese, not much.'] },
      { id: 'buzhidao', zh: '我不知道', py: 'wǒ bù zhīdào', en: 'I don\'t know', ex: ['他在哪里？我不知道。', 'Tā zài nǎlǐ? Wǒ bù zhīdào.', 'Where is he? I don\'t know.'], lit: 'I not know' },
      { id: 'dengyixia', zh: '等一下', py: 'děng yíxià', en: 'wait a moment', ex: ['请等一下。', 'Qǐng děng yíxià.', 'Please wait a moment.'] },
      { id: 'qing', zh: '请', py: 'qǐng', en: 'please', ex: ['请进！', 'Qǐng jìn!', 'Please come in!'] },
      { id: 'keyima', zh: '可以吗？', py: 'kěyǐ ma?', en: 'is that okay? / may I?', ex: ['我坐这里，可以吗？', 'Wǒ zuò zhèlǐ, kěyǐ ma?', 'May I sit here?'] },
    ],
  },
  {
    id: 'u6', title: 'Family & people', emoji: '👨‍👩‍👧',
    items: [
      { id: 'baba', zh: '爸爸', py: 'bàba', en: 'dad', ex: ['我爸爸是医生。', 'Wǒ bàba shì yīshēng.', 'My dad is a doctor.'] },
      { id: 'mama', zh: '妈妈', py: 'māma', en: 'mom', ex: ['我妈妈很好。', 'Wǒ māma hěn hǎo.', 'My mom is well.'] },
      { id: 'pengyou', zh: '朋友', py: 'péngyou', en: 'friend', ex: ['他是我的好朋友。', 'Tā shì wǒ de hǎo péngyou.', 'He\'s my good friend.'] },
      { id: 'laoshi', zh: '老师', py: 'lǎoshī', en: 'teacher', ex: ['我的老师是中国人。', 'Wǒ de lǎoshī shì Zhōngguó rén.', 'My teacher is Chinese.'] },
      { id: 'xuesheng', zh: '学生', py: 'xuésheng', en: 'student', ex: ['你是学生吗？', 'Nǐ shì xuésheng ma?', 'Are you a student?'] },
      { id: 'de', zh: '的', py: 'de', en: '\'s (possession)', ex: ['这是我的手机。', 'Zhè shì wǒ de shǒujī.', 'This is my phone.'], note: 'With family and close relationships, 的 is usually left out: 我妈妈, 我家.' },
      { id: 'you', zh: '有', py: 'yǒu', en: 'to have / there is', ex: ['我有一个哥哥。', 'Wǒ yǒu yí ge gēge.', 'I have an older brother.'] },
      { id: 'meiyou', zh: '没有', py: 'méiyǒu', en: 'not have / there isn\'t', ex: ['我没有时间。', 'Wǒ méiyǒu shíjiān.', 'I don\'t have time.'], note: 'Negate 有 with 没, never with 不.' },
      { id: 'gege', zh: '哥哥', py: 'gēge', en: 'older brother', ex: ['我哥哥二十岁。', 'Wǒ gēge èrshí suì.', 'My older brother is twenty.'] },
      { id: 'jiejie', zh: '姐姐', py: 'jiějie', en: 'older sister', ex: ['她是我姐姐。', 'Tā shì wǒ jiějie.', 'She is my older sister.'] },
      { id: 'jikouren', zh: '你家有几口人？', py: 'nǐ jiā yǒu jǐ kǒu rén?', en: 'how many people are in your family?', ex: ['你家有几口人？——四口人。', 'Nǐ jiā yǒu jǐ kǒu rén? — Sì kǒu rén.', 'How many in your family? — Four.'], lit: 'your family has how many mouths of people?' },
    ],
  },
  {
    id: 'u7', title: 'Where are you from?', emoji: '🌍',
    items: [
      { id: 'narenr', zh: '你是哪国人？', py: 'nǐ shì nǎ guó rén?', en: 'what country are you from?', ex: ['你是哪国人？——我是英国人。', 'Nǐ shì nǎ guó rén? — Wǒ shì Yīngguó rén.', 'Where are you from? — I\'m British.'], lit: 'you are which country person?' },
      { id: 'zhongguo', zh: '中国', py: 'Zhōngguó', en: 'China', ex: ['我想去中国。', 'Wǒ xiǎng qù Zhōngguó.', 'I want to go to China.'], lit: 'middle country' },
      { id: 'zhongwen', zh: '中文', py: 'Zhōngwén', en: 'Chinese (language)', ex: ['我在学中文。', 'Wǒ zài xué Zhōngwén.', 'I\'m learning Chinese.'] },
      { id: 'yingwen', zh: '英文', py: 'Yīngwén', en: 'English (language)', ex: ['你会说英文吗？', 'Nǐ huì shuō Yīngwén ma?', 'Can you speak English?'] },
      { id: 'meiguo', zh: '美国', py: 'Měiguó', en: 'USA', ex: ['他是美国人。', 'Tā shì Měiguó rén.', 'He is American.'], lit: 'beautiful country' },
      { id: 'yingguo', zh: '英国', py: 'Yīngguó', en: 'UK', ex: ['我住在英国。', 'Wǒ zhù zài Yīngguó.', 'I live in the UK.'] },
      { id: 'ren', zh: '人', py: 'rén', en: 'person', ex: ['中国人', 'Zhōngguó rén', 'Chinese person'], note: 'Country + 人 = a person from that country.' },
      { id: 'zhuzai', zh: '住在…', py: 'zhù zài…', en: 'to live in…', ex: ['你住在哪里？', 'Nǐ zhù zài nǎlǐ?', 'Where do you live?'], lit: 'live at…' },
      { id: 'xue', zh: '学', py: 'xué', en: 'to study / learn', ex: ['我每天学中文。', 'Wǒ měitiān xué Zhōngwén.', 'I study Chinese every day.'] },
      { id: 'huishuo2', zh: '会说', py: 'huì shuō', en: 'can speak', ex: ['她会说三种语言。', 'Tā huì shuō sān zhǒng yǔyán.', 'She can speak three languages.'], note: '会 is "can" for a learned skill, like speaking a language. To ask permission ("may I?"), use 可以.' },
    ],
  },
  {
    id: 'u8', title: 'Food & drink', emoji: '🍜',
    items: [
      { id: 'chi', zh: '吃', py: 'chī', en: 'to eat', ex: ['你想吃什么？', 'Nǐ xiǎng chī shénme?', 'What do you want to eat?'] },
      { id: 'he', zh: '喝', py: 'hē', en: 'to drink', ex: ['你喝什么？', 'Nǐ hē shénme?', 'What will you drink?'] },
      { id: 'xiang', zh: '想', py: 'xiǎng', en: 'to want to / would like', ex: ['我想喝水。', 'Wǒ xiǎng hē shuǐ.', 'I\'d like some water.'] },
      { id: 'yao', zh: '要', py: 'yào', en: 'to want (to order)', ex: ['我要这个。', 'Wǒ yào zhège.', 'I\'ll have this one.'], note: '要 is direct ("I want", "I\'ll have") and normal when ordering. 想 is softer ("I\'d like to").' },
      { id: 'shui', zh: '水', py: 'shuǐ', en: 'water', ex: ['请给我一杯水。', 'Qǐng gěi wǒ yì bēi shuǐ.', 'A glass of water, please.'] },
      { id: 'cha', zh: '茶', py: 'chá', en: 'tea', ex: ['我喜欢喝茶。', 'Wǒ xǐhuan hē chá.', 'I like drinking tea.'] },
      { id: 'kafei', zh: '咖啡', py: 'kāfēi', en: 'coffee', ex: ['一杯咖啡，谢谢。', 'Yì bēi kāfēi, xièxie.', 'A coffee, thanks.'] },
      { id: 'mifan', zh: '米饭', py: 'mǐfàn', en: 'rice (cooked)', ex: ['我要一碗米饭。', 'Wǒ yào yì wǎn mǐfàn.', 'I\'d like a bowl of rice.'], lit: 'rice meal' },
      { id: 'haochi', zh: '好吃', py: 'hǎochī', en: 'tasty', ex: ['这个很好吃！', 'Zhège hěn hǎochī!', 'This is really tasty!'], lit: 'good (to) eat' },
      { id: 'maidan', zh: '买单', py: 'mǎidān', en: 'the bill, please', ex: ['服务员，买单！', 'Fúwùyuán, mǎidān!', 'Waiter, the bill please!'], lit: 'buy the bill' },
      { id: 'buyaola', zh: '不要辣', py: 'bú yào là', en: 'not spicy, please', ex: ['我不要辣，谢谢。', 'Wǒ bú yào là, xièxie.', 'No spice for me, thanks.'], lit: 'not want spicy' },
      { id: 'xihuan', zh: '喜欢', py: 'xǐhuan', en: 'to like', ex: ['你喜欢中国菜吗？', 'Nǐ xǐhuan Zhōngguó cài ma?', 'Do you like Chinese food?'] },
    ],
  },
  {
    id: 'u9', title: 'Shopping & money', emoji: '🛍️',
    items: [
      { id: 'duoshaoqian', zh: '多少钱？', py: 'duōshao qián?', en: 'how much does it cost?', ex: ['这个多少钱？', 'Zhège duōshao qián?', 'How much is this?'], lit: 'many-few money?' },
      { id: 'kuai', zh: '块', py: 'kuài', en: 'yuan (spoken)', ex: ['十五块。', 'Shíwǔ kuài.', 'Fifteen yuan.'] },
      { id: 'tai_gui', zh: '太贵了', py: 'tài guì le', en: 'too expensive', ex: ['太贵了，便宜一点吧。', 'Tài guì le, piányi yìdiǎn ba.', 'Too expensive, make it a bit cheaper.'], note: '太 … 了 means "too …", or for good things "so …": 太贵了 too expensive, 太好了 great!' },
      { id: 'pianyi', zh: '便宜', py: 'piányi', en: 'cheap', ex: ['这个很便宜。', 'Zhège hěn piányi.', 'This one is cheap.'] },
      { id: 'mai', zh: '买', py: 'mǎi', en: 'to buy', ex: ['我想买这个。', 'Wǒ xiǎng mǎi zhège.', 'I want to buy this.'], note: '买 mǎi (buy) and 卖 mài (sell) differ only in tone.' },
      { id: 'zhege', zh: '这个', py: 'zhège', en: 'this one', ex: ['我要这个。', 'Wǒ yào zhège.', 'I want this one.'], note: 'In everyday speech often zhèige (and 那个 nèige).' },
      { id: 'nage', zh: '那个', py: 'nàge', en: 'that one', ex: ['那个是什么？', 'Nàge shì shénme?', 'What is that?'] },
      { id: 'weixin', zh: '可以用微信吗？', py: 'kěyǐ yòng Wēixìn ma?', en: 'can I pay with WeChat?', ex: ['可以用微信付钱吗？', 'Kěyǐ yòng Wēixìn fù qián ma?', 'Can I pay with WeChat?'] },
      { id: 'kankan', zh: '我看看', py: 'wǒ kànkan', en: 'I\'m just looking', ex: ['谢谢，我先看看。', 'Xièxie, wǒ xiān kànkan.', 'Thanks, I\'m just looking first.'], note: 'Saying a verb twice makes it light and brief: 看看 is "have a quick look".', lit: 'I look look' },
      { id: 'buyao', zh: '不要', py: 'bú yào', en: 'don\'t want / no thanks', ex: ['不要，谢谢。', 'Bú yào, xièxie.', 'No thanks.'] },
    ],
  },
  {
    id: 'u10', title: 'Time & days', emoji: '🕐',
    items: [
      { id: 'jintian', zh: '今天', py: 'jīntiān', en: 'today', ex: ['今天很忙。', 'Jīntiān hěn máng.', 'Today is busy.'] },
      { id: 'mingtian', zh: '明天', py: 'míngtiān', en: 'tomorrow', ex: ['明天你有时间吗？', 'Míngtiān nǐ yǒu shíjiān ma?', 'Are you free tomorrow?'], note: 'Time words go before the verb, never at the end as in English: 明天你有时间吗？ or 你明天有时间吗？' },
      { id: 'zuotian', zh: '昨天', py: 'zuótiān', en: 'yesterday', ex: ['昨天我很累。', 'Zuótiān wǒ hěn lèi.', 'I was tired yesterday.'] },
      { id: 'xianzai', zh: '现在', py: 'xiànzài', en: 'now', ex: ['现在几点？', 'Xiànzài jǐ diǎn?', 'What time is it now?'] },
      { id: 'jidian', zh: '几点？', py: 'jǐ diǎn?', en: 'what time?', ex: ['我们几点见？', 'Wǒmen jǐ diǎn jiàn?', 'What time shall we meet?'], lit: 'how many o\'clock?' },
      { id: 'dian', zh: '点', py: 'diǎn', en: 'o\'clock', ex: ['三点半', 'sān diǎn bàn', 'half past three'] },
      { id: 'ban', zh: '半', py: 'bàn', en: 'half', ex: ['七点半起床。', 'Qī diǎn bàn qǐchuáng.', 'Get up at 7:30.'] },
      { id: 'shijian', zh: '时间', py: 'shíjiān', en: 'time', ex: ['你有时间吗？', 'Nǐ yǒu shíjiān ma?', 'Do you have time?'] },
      { id: 'zhoumo', zh: '周末', py: 'zhōumò', en: 'weekend', ex: ['周末你做什么？', 'Zhōumò nǐ zuò shénme?', 'What are you doing this weekend?'] },
      { id: 'xingqi', zh: '星期一', py: 'xīngqī yī', en: 'Monday', ex: ['星期一我上班。', 'Xīngqī yī wǒ shàngbān.', 'I work on Monday.'], note: '星期 + number: 一 Monday … 六 Saturday; Sunday is 星期天.' },
    ],
  },
  {
    id: 'u11', title: 'Getting around', emoji: '🚕',
    items: [
      { id: 'qu', zh: '去', py: 'qù', en: 'to go', ex: ['你去哪里？', 'Nǐ qù nǎlǐ?', 'Where are you going?'] },
      { id: 'zai', zh: '在', py: 'zài', en: 'to be at / in', ex: ['我在家。', 'Wǒ zài jiā.', 'I\'m at home.'], note: 'Before another verb, 在 means "in the middle of doing": 我在学中文 (I\'m learning Chinese).' },
      { id: 'zhelinali', zh: '这里 / 那里', py: 'zhèlǐ / nàlǐ', en: 'here / there', ex: ['请在这里停。', 'Qǐng zài zhèlǐ tíng.', 'Please stop here.'], note: '那里 nàlǐ (there) and 哪里 nǎlǐ (where?) differ only in tone.' },
      { id: 'zuozhuan', zh: '左转', py: 'zuǒ zhuǎn', en: 'turn left', ex: ['前面左转。', 'Qiánmiàn zuǒ zhuǎn.', 'Turn left up ahead.'] },
      { id: 'youzhuan', zh: '右转', py: 'yòu zhuǎn', en: 'turn right', ex: ['第二个路口右转。', 'Dì èr ge lùkǒu yòu zhuǎn.', 'Turn right at the second intersection.'] },
      { id: 'yizhizou', zh: '一直走', py: 'yìzhí zǒu', en: 'go straight', ex: ['一直走，就到了。', 'Yìzhí zǒu, jiù dào le.', 'Go straight and you\'re there.'] },
      { id: 'yuan', zh: '远吗？', py: 'yuǎn ma?', en: 'is it far?', ex: ['地铁站远吗？', 'Dìtiě zhàn yuǎn ma?', 'Is the subway station far?'] },
      { id: 'ditie', zh: '地铁', py: 'dìtiě', en: 'subway', ex: ['我坐地铁去。', 'Wǒ zuò dìtiě qù.', 'I\'ll take the subway.'], lit: 'ground iron' },
      { id: 'xishoujian', zh: '洗手间', py: 'xǐshǒujiān', en: 'restroom', ex: ['请问，洗手间在哪里？', 'Qǐngwèn, xǐshǒujiān zài nǎlǐ?', 'Excuse me, where\'s the restroom?'], lit: 'wash-hands room' },
      { id: 'qingwen', zh: '请问', py: 'qǐngwèn', en: 'excuse me (may I ask)', ex: ['请问，这是哪里？', 'Qǐngwèn, zhè shì nǎlǐ?', 'Excuse me, where am I?'], note: 'The "excuse me" before a question. For "excuse me, sorry", use 对不起.', lit: 'please ask' },
    ],
  },
  {
    id: 'u12', title: 'Feelings & chatting', emoji: '💬',
    items: [
      { id: 'lei', zh: '累', py: 'lèi', en: 'tired', ex: ['我今天很累。', 'Wǒ jīntiān hěn lèi.', 'I\'m tired today.'] },
      { id: 'e', zh: '饿', py: 'è', en: 'hungry', ex: ['你饿了吗？', 'Nǐ è le ma?', 'Are you hungry?'] },
      { id: 'mang', zh: '忙', py: 'máng', en: 'busy', ex: ['你忙吗？——不太忙。', 'Nǐ máng ma? — Bú tài máng.', 'Are you busy? — Not too busy.'] },
      { id: 'gaoxing', zh: '高兴', py: 'gāoxìng', en: 'happy / glad', ex: ['我很高兴。', 'Wǒ hěn gāoxìng.', 'I\'m happy.'], lit: 'high mood' },
      { id: 'taihaole', zh: '太好了！', py: 'tài hǎo le!', en: 'great! / wonderful!', ex: ['你来了？太好了！', 'Nǐ lái le? Tài hǎo le!', 'You came? Great!'], lit: 'too good!' },
      { id: 'zhende', zh: '真的吗？', py: 'zhēn de ma?', en: 'really?', ex: ['真的吗？我不知道！', 'Zhēn de ma? Wǒ bù zhīdào!', 'Really? I didn\'t know!'] },
      { id: 'juede', zh: '我觉得…', py: 'wǒ juéde…', en: 'I think / I feel…', ex: ['我觉得中文很有意思。', 'Wǒ juéde Zhōngwén hěn yǒu yìsi.', 'I think Chinese is interesting.'] },
      { id: 'youyisi', zh: '有意思', py: 'yǒu yìsi', en: 'interesting / fun', ex: ['这个电影很有意思。', 'Zhège diànyǐng hěn yǒu yìsi.', 'This movie is really interesting.'], lit: 'has meaning' },
      { id: 'yiqi', zh: '一起', py: 'yìqǐ', en: 'together', ex: ['我们一起吃饭吧。', 'Wǒmen yìqǐ chīfàn ba.', 'Let\'s eat together.'] },
      { id: 'ba_sugg', zh: '…吧', py: '… ba', en: 'let\'s… (suggestion)', ex: ['我们走吧！', 'Wǒmen zǒu ba!', 'Let\'s go!'], note: '吧 at the end softens a sentence into a suggestion.' },
      { id: 'jiayou', zh: '加油！', py: 'jiāyóu!', en: 'you can do it! / go for it!', ex: ['学中文，加油！', 'Xué Zhōngwén, jiāyóu!', 'Keep going with Chinese!'], lit: 'add oil!' },
    ],
  },
  {
    id: 'u13', title: 'My day', emoji: '⏰',
    items: [
      { id: 'qichuang', zh: '起床', py: 'qǐchuáng', en: 'to get up', ex: ['我每天七点起床。', 'Wǒ měitiān qī diǎn qǐchuáng.', 'I get up at seven every day.'], lit: 'rise (from) bed' },
      { id: 'shuijiao', zh: '睡觉', py: 'shuìjiào', en: 'to go to bed / sleep', ex: ['你几点睡觉？', 'Nǐ jǐ diǎn shuìjiào?', 'What time do you go to bed?'] },
      { id: 'meitian', zh: '每天', py: 'měitiān', en: 'every day', ex: ['他每天跑步。', 'Tā měitiān pǎobù.', 'He runs every day.'] },
      { id: 'wanshang', zh: '晚上', py: 'wǎnshang', en: 'evening / tonight', ex: ['晚上你做什么？', 'Wǎnshang nǐ zuò shénme?', 'What are you doing this evening?'] },
      { id: 'shangban', zh: '上班', py: 'shàngbān', en: 'to go to work', ex: ['我八点上班。', 'Wǒ bā diǎn shàngbān.', 'I start work at eight.'] },
      { id: 'xiaban', zh: '下班', py: 'xiàbān', en: 'to finish work', ex: ['你几点下班？', 'Nǐ jǐ diǎn xiàbān?', 'What time do you finish work?'], note: '上 and 下 (up and down) also mean starting and finishing: 上班 / 下班 start / finish work, 上课 / 下课 start / finish class.' },
      { id: 'zaofan', zh: '吃早饭', py: 'chī zǎofàn', en: 'to have breakfast', ex: ['我不吃早饭。', 'Wǒ bù chī zǎofàn.', 'I don\'t eat breakfast.'], note: '早饭, 午饭, 晚饭: breakfast, lunch and dinner (the morning, noon and evening meal).', lit: 'eat morning meal' },
      { id: 'huijia', zh: '回家', py: 'huí jiā', en: 'to go home', ex: ['我六点回家。', 'Wǒ liù diǎn huí jiā.', 'I go home at six.'], lit: 'return home' },
      { id: 'zuo', zh: '做', py: 'zuò', en: 'to do / make', ex: ['你在做什么？', 'Nǐ zài zuò shénme?', 'What are you doing?'] },
      { id: 'xizao', zh: '洗澡', py: 'xǐzǎo', en: 'to shower / bathe', ex: ['我晚上洗澡。', 'Wǒ wǎnshang xǐzǎo.', 'I shower in the evening.'] },
      { id: 'ranhou', zh: '然后', py: 'ránhòu', en: 'then / after that', ex: ['我先吃饭，然后洗澡。', 'Wǒ xiān chīfàn, ránhòu xǐzǎo.', 'I eat first, then shower.'], note: '先 … 然后 … is "first … then …".' },
    ],
  },
  {
    id: 'u14', title: 'Work & study', emoji: '💼',
    items: [
      { id: 'gongzuo', zh: '工作', py: 'gōngzuò', en: 'work / to work', ex: ['我在北京工作。', 'Wǒ zài Běijīng gōngzuò.', 'I work in Beijing.'], note: 'Where you do something goes before the verb, with 在: 我在北京工作, not 我工作在北京.' },
      { id: 'zuoshenmegongzuo', zh: '你做什么工作？', py: 'nǐ zuò shénme gōngzuò?', en: 'what do you do (for work)?', ex: ['你做什么工作？——我是老师。', 'Nǐ zuò shénme gōngzuò? — Wǒ shì lǎoshī.', 'What do you do? — I\'m a teacher.'], lit: 'you do what work?' },
      { id: 'gongsi', zh: '公司', py: 'gōngsī', en: 'company', ex: ['我在一家公司上班。', 'Wǒ zài yì jiā gōngsī shàngbān.', 'I work at a company.'], note: '家 is the measure word for companies, shops and restaurants.' },
      { id: 'tongshi', zh: '同事', py: 'tóngshì', en: 'colleague', ex: ['他是我的同事。', 'Tā shì wǒ de tóngshì.', 'He\'s my colleague.'] },
      { id: 'laoban', zh: '老板', py: 'lǎobǎn', en: 'boss', ex: ['我的老板人很好。', 'Wǒ de lǎobǎn rén hěn hǎo.', 'My boss is a nice person.'] },
      { id: 'shangke', zh: '上课', py: 'shàngkè', en: 'to have class', ex: ['我们九点上课。', 'Wǒmen jiǔ diǎn shàngkè.', 'Class starts at nine.'] },
      { id: 'kaoshi', zh: '考试', py: 'kǎoshì', en: 'exam / to take an exam', ex: ['明天我有考试。', 'Míngtiān wǒ yǒu kǎoshì.', 'I have an exam tomorrow.'] },
      { id: 'kaihui', zh: '开会', py: 'kāihuì', en: 'to have a meeting', ex: ['老板在开会。', 'Lǎobǎn zài kāihuì.', 'The boss is in a meeting.'], lit: 'open meeting' },
      { id: 'xiuxi', zh: '休息', py: 'xiūxi', en: 'to rest / take a break', ex: ['我们休息一下吧。', 'Wǒmen xiūxi yíxià ba.', 'Let\'s take a break.'], note: '一下 after a verb makes it brief and casual: 休息一下 "take a quick break", 等一下 "wait a moment".' },
      { id: 'mingbai', zh: '明白', py: 'míngbai', en: 'to understand / get it', ex: ['我明白了。', 'Wǒ míngbai le.', 'I get it now.'], note: '了 at the end says something has changed: you didn\'t get it before, and now you do.', lit: 'bright white' },
      { id: 'diannao', zh: '电脑', py: 'diànnǎo', en: 'computer', ex: ['我的电脑坏了。', 'Wǒ de diànnǎo huài le.', 'My computer is broken.'], lit: 'electric brain' },
    ],
  },
  {
    id: 'u15', title: 'Free time', emoji: '⚽',
    items: [
      { id: 'aihao', zh: '爱好', py: 'àihào', en: 'hobby', ex: ['你有什么爱好？', 'Nǐ yǒu shénme àihào?', 'What are your hobbies?'], lit: 'love (and) like' },
      { id: 'kandianying', zh: '看电影', py: 'kàn diànyǐng', en: 'to watch a movie', ex: ['周末我们去看电影吧。', 'Zhōumò wǒmen qù kàn diànyǐng ba.', 'Let\'s go and see a movie this weekend.'], note: '去 + verb is "go and do": 去看电影 "go and see a movie".', lit: 'look (at) electric shadows' },
      { id: 'tingyinyue', zh: '听音乐', py: 'tīng yīnyuè', en: 'to listen to music', ex: ['我喜欢听中国音乐。', 'Wǒ xǐhuan tīng Zhōngguó yīnyuè.', 'I like listening to Chinese music.'] },
      { id: 'yundong', zh: '运动', py: 'yùndòng', en: 'sport / to exercise', ex: ['你喜欢什么运动？', 'Nǐ xǐhuan shénme yùndòng?', 'What sports do you like?'] },
      { id: 'paobu', zh: '跑步', py: 'pǎobù', en: 'to go running', ex: ['我早上去跑步。', 'Wǒ zǎoshang qù pǎobù.', 'I go running in the mornings.'] },
      { id: 'youyong', zh: '游泳', py: 'yóuyǒng', en: 'to swim', ex: ['你会游泳吗？', 'Nǐ huì yóuyǒng ma?', 'Can you swim?'] },
      { id: 'changge', zh: '唱歌', py: 'chànggē', en: 'to sing', ex: ['她唱歌很好听。', 'Tā chànggē hěn hǎotīng.', 'She sings beautifully.'], note: '好听 is "nice to hear", like 好吃 (nice to eat) and 好看 (nice to look at).', lit: 'sing songs' },
      { id: 'kanshu', zh: '看书', py: 'kàn shū', en: 'to read (a book)', ex: ['我晚上喜欢看书。', 'Wǒ wǎnshang xǐhuan kàn shū.', 'I like reading in the evening.'], lit: 'look (at) books' },
      { id: 'lvyou', zh: '旅游', py: 'lǚyóu', en: 'to travel (for fun)', ex: ['我想去中国旅游。', 'Wǒ xiǎng qù Zhōngguó lǚyóu.', 'I\'d like to travel to China.'] },
      { id: 'wan', zh: '玩', py: 'wán', en: 'to have fun / go out / play', ex: ['周末你去哪里玩？', 'Zhōumò nǐ qù nǎlǐ wán?', 'Where are you going this weekend?'], note: '玩 covers having fun, going out, hanging out and playing games.' },
      { id: 'dalanqiu', zh: '打篮球', py: 'dǎ lánqiú', en: 'to play basketball', ex: ['我们一起打篮球吧。', 'Wǒmen yìqǐ dǎ lánqiú ba.', 'Let\'s play basketball together.'], note: 'Most ball games use 打 (hit): 打篮球, 打网球 (tennis). Football is 踢足球 tī zúqiú (kick).' },
    ],
  },
  {
    id: 'u16', title: 'Can, must & should', emoji: '💪',
    items: [
      { id: 'neng', zh: '能', py: 'néng', en: 'can / be able to', ex: ['你能帮我吗？', 'Nǐ néng bāng wǒ ma?', 'Can you help me?'], note: '能 is "able to" (nothing stops you). 会 is a skill you learned (我会游泳), and 可以 asks permission (我可以坐这里吗？).' },
      { id: 'bang', zh: '帮', py: 'bāng', en: 'to help', ex: ['我帮你拿。', 'Wǒ bāng nǐ ná.', 'Let me carry it for you.'] },
      { id: 'yinggai', zh: '应该', py: 'yīnggāi', en: 'should', ex: ['你应该休息。', 'Nǐ yīnggāi xiūxi.', 'You should rest.'] },
      { id: 'dei', zh: '我得走了', py: 'wǒ děi zǒu le', en: 'I have to go', ex: ['不早了，我得回家了。', 'Bù zǎo le, wǒ děi huí jiā le.', 'It\'s getting late, I have to go home.'], note: 'Meaning "have to", 得 is said děi. After a verb the same character is de (说得很好).' },
      { id: 'buyong', zh: '不用', py: 'bú yòng', en: 'no need to', ex: ['不用谢！', 'Bú yòng xiè!', 'No need to thank me!'], note: '不用谢 is another answer to 谢谢, like 不客气.', lit: 'not use' },
      { id: 'xuyao', zh: '需要', py: 'xūyào', en: 'to need', ex: ['你需要什么？', 'Nǐ xūyào shénme?', 'What do you need?'] },
      { id: 'tingdedong', zh: '听得懂', py: 'tīng de dǒng', en: 'can understand (what you hear)', ex: ['你听得懂中文吗？', 'Nǐ tīng de dǒng Zhōngwén ma?', 'Can you understand spoken Chinese?'], note: 'Verb + 得懂 / 不懂: can / can\'t understand. 听得懂 by listening, 看得懂 by reading.', lit: 'listen can understand' },
      { id: 'yiding', zh: '一定', py: 'yídìng', en: 'definitely', ex: ['我一定来。', 'Wǒ yídìng lái.', 'I\'ll definitely come.'] },
      { id: 'meibanfa', zh: '没办法', py: 'méi bànfǎ', en: 'it can\'t be helped', ex: ['没办法，我得上班。', 'Méi bànfǎ, wǒ děi shàngbān.', 'It can\'t be helped, I have to work.'], lit: 'there\'s no way' },
      { id: 'dangran', zh: '当然', py: 'dāngrán', en: 'of course', ex: ['当然可以！', 'Dāngrán kěyǐ!', 'Of course you can!'] },
      { id: 'shishi', zh: '试试', py: 'shìshi', en: 'to give it a try', ex: ['你试试这个。', 'Nǐ shìshi zhège.', 'Try this one.'], note: 'Saying a verb twice makes it light and brief, as in 看看: 试试 is "have a try".' },
    ],
  },
  {
    id: 'u17', title: 'Past & plans', emoji: '📆',
    items: [
      { id: 'chifanle', zh: '你吃饭了吗？', py: 'nǐ chīfàn le ma?', en: 'have you eaten?', ex: ['我吃饭了，你呢？', 'Wǒ chīfàn le, nǐ ne?', 'I\'ve eaten, how about you?'], note: '了 after a verb says it\'s done. "Have you eaten?" is also a friendly way to say hello.' },
      { id: 'haimei', zh: '还没', py: 'hái méi', en: 'not yet', ex: ['我还没吃饭。', 'Wǒ hái méi chīfàn.', 'I haven\'t eaten yet.'], note: 'For something that didn\'t happen, use 没 (not 不), and no 了: 我没去 "I didn\'t go".' },
      { id: 'yijing', zh: '已经', py: 'yǐjīng', en: 'already', ex: ['我已经到了。', 'Wǒ yǐjīng dào le.', 'I\'m already here.'] },
      { id: 'quguo', zh: '去过', py: 'qù guo', en: 'have been to', ex: ['你去过中国吗？', 'Nǐ qù guo Zhōngguó ma?', 'Have you ever been to China?'], note: 'Verb + 过: you\'ve done it at some point. 我去过北京 "I\'ve been to Beijing", 我吃过 "I\'ve tried it".' },
      { id: 'dasuan', zh: '打算', py: 'dǎsuan', en: 'to plan to', ex: ['周末你打算做什么？', 'Zhōumò nǐ dǎsuan zuò shénme?', 'What are you planning to do this weekend?'] },
      { id: 'yihou', zh: '以后', py: 'yǐhòu', en: 'in the future / later', ex: ['以后我想去中国工作。', 'Yǐhòu wǒ xiǎng qù Zhōngguó gōngzuò.', 'In the future I\'d like to work in China.'] },
      { id: 'qunian', zh: '去年', py: 'qùnián', en: 'last year', ex: ['我去年开始学中文。', 'Wǒ qùnián kāishǐ xué Zhōngwén.', 'I started learning Chinese last year.'], lit: 'gone year' },
      { id: 'mingnian', zh: '明年', py: 'míngnián', en: 'next year', ex: ['明年我们去旅游。', 'Míngnián wǒmen qù lǚyóu.', 'Next year we\'re going travelling.'] },
      { id: 'shanggexingqi', zh: '上个星期', py: 'shàng ge xīngqī', en: 'last week', ex: ['上个星期我很忙。', 'Shàng ge xīngqī wǒ hěn máng.', 'I was busy last week.'], note: '上个 is "last" and 下个 is "next": 上个月 last month, 下个星期 next week.' },
      { id: 'gangcai', zh: '刚才', py: 'gāngcái', en: 'just now', ex: ['你刚才说什么？', 'Nǐ gāngcái shuō shénme?', 'What did you just say?'] },
      { id: 'mashang', zh: '马上', py: 'mǎshàng', en: 'right away', ex: ['我马上来！', 'Wǒ mǎshàng lái!', 'I\'m coming right away!'], lit: 'on horseback' },
    ],
  },
  {
    id: 'u18', title: 'Weather', emoji: '🌤️',
    items: [
      { id: 'tianqi', zh: '天气', py: 'tiānqì', en: 'weather', ex: ['今天天气很好。', 'Jīntiān tiānqì hěn hǎo.', 'The weather\'s nice today.'] },
      { id: 'leng', zh: '冷', py: 'lěng', en: 'cold', ex: ['外面很冷。', 'Wàimiàn hěn lěng.', 'It\'s cold outside.'] },
      { id: 're', zh: '热', py: 'rè', en: 'hot', ex: ['今天太热了！', 'Jīntiān tài rè le!', 'It\'s so hot today!'] },
      { id: 'xiayu', zh: '下雨', py: 'xià yǔ', en: 'to rain', ex: ['外面在下雨。', 'Wàimiàn zài xià yǔ.', 'It\'s raining outside.'], lit: 'fall rain' },
      { id: 'xiaxue', zh: '下雪', py: 'xià xuě', en: 'to snow', ex: ['北京冬天下雪吗？', 'Běijīng dōngtiān xià xuě ma?', 'Does it snow in Beijing in winter?'], lit: 'fall snow' },
      { id: 'qingtian', zh: '晴天', py: 'qíngtiān', en: 'sunny day', ex: ['明天是晴天。', 'Míngtiān shì qíngtiān.', 'Tomorrow will be sunny.'] },
      { id: 'xiatian', zh: '夏天', py: 'xiàtiān', en: 'summer', ex: ['我喜欢夏天。', 'Wǒ xǐhuan xiàtiān.', 'I like summer.'] },
      { id: 'dongtian', zh: '冬天', py: 'dōngtiān', en: 'winter', ex: ['这里冬天很冷。', 'Zhèlǐ dōngtiān hěn lěng.', 'Winters here are cold.'], note: 'The four seasons: 春天 chūntiān spring, 夏天 summer, 秋天 qiūtiān autumn, 冬天 winter.' },
      { id: 'duoshaodu', zh: '多少度？', py: 'duōshao dù?', en: 'what\'s the temperature?', ex: ['今天多少度？——三十度。', 'Jīntiān duōshao dù? — Sānshí dù.', 'What\'s the temperature today? — Thirty degrees.'], note: 'Temperatures are in Celsius, so 三十度 is hot.', lit: 'how many degrees?' },
      { id: 'daisan', zh: '带伞', py: 'dài sǎn', en: 'to take an umbrella', ex: ['下雨了，带伞吧。', 'Xià yǔ le, dài sǎn ba.', 'It\'s started raining, take an umbrella.'], note: '了 at the end of a sentence says something has changed: 下雨了 "it\'s started raining".' },
      { id: 'shufu', zh: '舒服', py: 'shūfu', en: 'comfortable / pleasant', ex: ['今天天气很舒服。', 'Jīntiān tiānqì hěn shūfu.', 'The weather\'s really pleasant today.'] },
    ],
  },
  {
    id: 'u19', title: 'Around town', emoji: '🏙️',
    items: [
      { id: 'fujin', zh: '附近', py: 'fùjìn', en: 'nearby', ex: ['附近有超市吗？', 'Fùjìn yǒu chāoshì ma?', 'Is there a supermarket nearby?'], note: '"There\'s a … at / near …" is place + 有 + thing: 附近有超市.' },
      { id: 'chaoshi', zh: '超市', py: 'chāoshì', en: 'supermarket', ex: ['我去超市买水果。', 'Wǒ qù chāoshì mǎi shuǐguǒ.', 'I\'m going to the supermarket to buy fruit.'] },
      { id: 'yinhang', zh: '银行', py: 'yínháng', en: 'bank', ex: ['银行几点开门？', 'Yínháng jǐ diǎn kāimén?', 'What time does the bank open?'] },
      { id: 'yiyuan', zh: '医院', py: 'yīyuàn', en: 'hospital', ex: ['最近的医院在哪里？', 'Zuìjìn de yīyuàn zài nǎlǐ?', 'Where\'s the nearest hospital?'] },
      { id: 'fanguan', zh: '饭馆', py: 'fànguǎn', en: 'restaurant', ex: ['这家饭馆很好吃。', 'Zhè jiā fànguǎn hěn hǎochī.', 'The food at this restaurant is great.'], lit: 'meal house' },
      { id: 'pangbian', zh: '旁边', py: 'pángbiān', en: 'next to', ex: ['银行在超市旁边。', 'Yínháng zài chāoshì pángbiān.', 'The bank is next to the supermarket.'], note: 'Thing + 在 + place + 旁边 / 对面 / 里面 says where something is: next to, across from, inside.' },
      { id: 'duimian', zh: '对面', py: 'duìmiàn', en: 'across from / opposite', ex: ['医院在学校对面。', 'Yīyuàn zài xuéxiào duìmiàn.', 'The hospital is across from the school.'] },
      { id: 'limian', zh: '里面', py: 'lǐmiàn', en: 'inside', ex: ['他在里面等你。', 'Tā zài lǐmiàn děng nǐ.', 'He\'s waiting for you inside.'] },
      { id: 'huochezhan', zh: '火车站', py: 'huǒchēzhàn', en: 'train station', ex: ['火车站离这里远吗？', 'Huǒchēzhàn lí zhèlǐ yuǎn ma?', 'Is the train station far from here?'], note: 'A 离 B 远 / 近: A is far from / close to B.', lit: 'fire vehicle station' },
      { id: 'jichang', zh: '机场', py: 'jīchǎng', en: 'airport', ex: ['我打车去机场。', 'Wǒ dǎchē qù jīchǎng.', 'I\'m taking a taxi to the airport.'], note: '打车 is the everyday way to say "take a taxi".', lit: 'machine field' },
      { id: 'zenmezou', zh: '怎么走？', py: 'zěnme zǒu?', en: 'how do I get there?', ex: ['请问，地铁站怎么走？', 'Qǐngwèn, dìtiě zhàn zěnme zǒu?', 'Excuse me, how do I get to the subway station?'], lit: 'how walk?' },
    ],
  },
  {
    id: 'u20', title: 'Health', emoji: '🏥',
    items: [
      { id: 'bushufu', zh: '不舒服', py: 'bù shūfu', en: 'unwell', ex: ['我今天不舒服。', 'Wǒ jīntiān bù shūfu.', 'I don\'t feel well today.'], lit: 'not comfortable' },
      { id: 'shengbing', zh: '生病', py: 'shēngbìng', en: 'to be ill', ex: ['他生病了，今天不来。', 'Tā shēngbìng le, jīntiān bù lái.', 'He\'s ill, he\'s not coming today.'] },
      { id: 'touteng', zh: '头疼', py: 'tóuténg', en: 'headache', ex: ['我头疼，想休息。', 'Wǒ tóuténg, xiǎng xiūxi.', 'I have a headache and want to rest.'], note: 'Body part + 疼 says what hurts: 头疼 headache, 肚子疼 dùzi téng stomach ache.', lit: 'head hurts' },
      { id: 'ganmao', zh: '感冒', py: 'gǎnmào', en: 'a cold / to catch a cold', ex: ['我感冒了。', 'Wǒ gǎnmào le.', 'I\'ve caught a cold.'] },
      { id: 'fashao', zh: '发烧', py: 'fāshāo', en: 'to have a fever', ex: ['你发烧了吗？', 'Nǐ fāshāo le ma?', 'Do you have a fever?'] },
      { id: 'kanyisheng', zh: '看医生', py: 'kàn yīshēng', en: 'to see a doctor', ex: ['你应该去看医生。', 'Nǐ yīnggāi qù kàn yīshēng.', 'You should go and see a doctor.'] },
      { id: 'chiyao', zh: '吃药', py: 'chī yào', en: 'to take medicine', ex: ['你吃药了吗？', 'Nǐ chī yào le ma?', 'Have you taken your medicine?'], note: 'Medicine is "eaten" in Chinese, even when it\'s a drink.', lit: 'eat medicine' },
      { id: 'shenti', zh: '身体', py: 'shēntǐ', en: 'body / health', ex: ['你身体好吗？', 'Nǐ shēntǐ hǎo ma?', 'Are you keeping well?'], note: '身体 is also how you talk about health: 身体很好 "in good health".' },
      { id: 'duoheshui', zh: '多喝水', py: 'duō hē shuǐ', en: 'drink plenty of water', ex: ['你要多喝水。', 'Nǐ yào duō hē shuǐ.', 'You should drink lots of water.'], note: '多 before a verb: do more of it. 多喝水 is the classic Chinese advice for any illness.', lit: 'much drink water' },
      { id: 'xiaoxin', zh: '小心', py: 'xiǎoxīn', en: 'be careful', ex: ['小心，地上有水！', 'Xiǎoxīn, dìshang yǒu shuǐ!', 'Careful, there\'s water on the floor!'], lit: 'small heart' },
      { id: 'haoduole', zh: '好多了', py: 'hǎo duō le', en: 'much better', ex: ['谢谢，我好多了。', 'Xièxie, wǒ hǎo duō le.', 'Thanks, I\'m much better.'] },
    ],
  },
  {
    id: 'u21', title: 'Phone & plans', emoji: '📱',
    items: [
      { id: 'dadianhua', zh: '打电话', py: 'dǎ diànhuà', en: 'to make a phone call', ex: ['我晚上给你打电话。', 'Wǒ wǎnshang gěi nǐ dǎ diànhuà.', 'I\'ll call you this evening.'], note: '给 + person + 打电话: to call someone.' },
      { id: 'wei', zh: '喂，你好！', py: 'wéi, nǐ hǎo!', en: 'hello? (answering the phone)', ex: ['喂，请问你是哪位？', 'Wéi, qǐngwèn nǐ shì nǎ wèi?', 'Hello? Who\'s calling, please?'], note: '喂 wéi is for the phone. 哪位 is a polite way to ask 谁.' },
      { id: 'shoujihao', zh: '手机号', py: 'shǒujī hào', en: 'mobile number', ex: ['你的手机号是多少？', 'Nǐ de shǒujī hào shì duōshao?', 'What\'s your mobile number?'], note: 'Ask for any number with 多少, not 什么.' },
      { id: 'jiaweixin', zh: '加微信', py: 'jiā Wēixìn', en: 'to add on WeChat', ex: ['我们加个微信吧。', 'Wǒmen jiā ge Wēixìn ba.', 'Let\'s add each other on WeChat.'] },
      { id: 'youkong', zh: '有空', py: 'yǒu kòng', en: 'to be free (have time)', ex: ['你今天晚上有空吗？', 'Nǐ jīntiān wǎnshang yǒu kòng ma?', 'Are you free tonight?'], lit: 'have empty (time)' },
      { id: 'dengni', zh: '我等你', py: 'wǒ děng nǐ', en: 'I\'ll wait for you', ex: ['我在门口等你。', 'Wǒ zài ménkǒu děng nǐ.', 'I\'ll wait for you at the entrance.'] },
      { id: 'daole', zh: '到了', py: 'dào le', en: 'I\'m here (I\'ve arrived)', ex: ['我到了，你在哪里？', 'Wǒ dào le, nǐ zài nǎlǐ?', 'I\'m here, where are you?'] },
      { id: 'chidao', zh: '迟到', py: 'chídào', en: 'to be late', ex: ['对不起，我要迟到了。', 'Duìbuqǐ, wǒ yào chídào le.', 'Sorry, I\'m going to be late.'], note: '要 … 了 says something is about to happen.' },
      { id: 'faxinxi', zh: '发信息', py: 'fā xìnxī', en: 'to send a message', ex: ['到了给我发信息。', 'Dào le gěi wǒ fā xìnxī.', 'Message me when you get there.'] },
      { id: 'bujianbusan', zh: '不见不散', py: 'bú jiàn bú sàn', en: 'see you there! (I\'ll wait)', ex: ['明天七点，不见不散！', 'Míngtiān qī diǎn, bú jiàn bú sàn!', 'Tomorrow at seven, see you there!'], lit: 'if we don\'t meet, we don\'t leave' },
      { id: 'yiyanweiding', zh: '一言为定', py: 'yì yán wéi dìng', en: 'it\'s a deal', ex: ['好，一言为定！', 'Hǎo, yì yán wéi dìng!', 'OK, it\'s a deal!'], lit: 'one word settles it' },
    ],
  },
  {
    id: 'u22', title: 'At the restaurant', emoji: '🥢',
    items: [
      { id: 'jiwei', zh: '几位？', py: 'jǐ wèi?', en: 'how many of you?', ex: ['你们几位？——两位。', 'Nǐmen jǐ wèi? — Liǎng wèi.', 'How many of you? — Two.'], note: '位 is the polite measure word for people.' },
      { id: 'fuwuyuan', zh: '服务员', py: 'fúwùyuán', en: 'waiter / waitress', ex: ['服务员，点菜！', 'Fúwùyuán, diǎn cài!', 'Excuse me, we\'d like to order!'], note: 'In China you call the staff over by saying 服务员 out loud, and that\'s not rude.' },
      { id: 'caidan', zh: '菜单', py: 'càidān', en: 'menu', ex: ['请给我们菜单。', 'Qǐng gěi wǒmen càidān.', 'Could we have the menu, please?'] },
      { id: 'diancai', zh: '点菜', py: 'diǎn cài', en: 'to order (food)', ex: ['我们现在点菜。', 'Wǒmen xiànzài diǎn cài.', 'We\'ll order now.'] },
      { id: 'la', zh: '辣', py: 'là', en: 'spicy', ex: ['这个菜辣不辣？', 'Zhège cài là bu là?', 'Is this dish spicy?'], note: 'A word, then 不 and the word again, asks a yes/no question: 辣不辣？ is the same as 辣吗？' },
      { id: 'chisu', zh: '我吃素', py: 'wǒ chī sù', en: 'I\'m vegetarian', ex: ['我吃素，不吃肉。', 'Wǒ chī sù, bù chī ròu.', 'I\'m vegetarian, I don\'t eat meat.'], lit: 'I eat plain' },
      { id: 'zailai', zh: '再来一个', py: 'zài lái yí ge', en: 'one more, please', ex: ['米饭再来一碗。', 'Mǐfàn zài lái yì wǎn.', 'Another bowl of rice, please.'], note: '来 is the casual way to order: 来一个 "I\'ll have one".', lit: 'again come one' },
      { id: 'bao', zh: '饱', py: 'bǎo', en: 'full (after eating)', ex: ['我吃饱了。', 'Wǒ chī bǎo le.', 'I\'m full.'] },
      { id: 'dabao', zh: '打包', py: 'dǎbāo', en: 'to take away / box up', ex: ['这个可以打包吗？', 'Zhège kěyǐ dǎbāo ma?', 'Can I take this away?'] },
      { id: 'ganbei', zh: '干杯', py: 'gānbēi', en: 'cheers!', ex: ['为我们的友谊干杯！', 'Wèi wǒmen de yǒuyì gānbēi!', 'To our friendship, cheers!'], lit: 'dry cup' },
      { id: 'qingke', zh: '我请客', py: 'wǒ qǐngkè', en: 'it\'s my treat', ex: ['今天我请客！', 'Jīntiān wǒ qǐngkè!', 'Today it\'s on me!'] },
    ],
  },
  {
    id: 'u23', title: 'Describing things', emoji: '📏',
    items: [
      { id: 'da', zh: '大', py: 'dà', en: 'big', ex: ['这个房间很大。', 'Zhège fángjiān hěn dà.', 'This room is big.'] },
      { id: 'xiao', zh: '小', py: 'xiǎo', en: 'small', ex: ['我的房间太小了。', 'Wǒ de fángjiān tài xiǎo le.', 'My room is too small.'] },
      { id: 'duo', zh: '多', py: 'duō', en: 'many / a lot', ex: ['这里人很多。', 'Zhèlǐ rén hěn duō.', 'There are lots of people here.'], note: '"Lots of people" is 人很多 or 很多人. 多 on its own doesn\'t go before a noun (not 多人).' },
      { id: 'shao', zh: '少', py: 'shǎo', en: 'few / not much', ex: ['今天人很少。', 'Jīntiān rén hěn shǎo.', 'There aren\'t many people today.'] },
      { id: 'xin', zh: '新', py: 'xīn', en: 'new', ex: ['这是我的新手机。', 'Zhè shì wǒ de xīn shǒujī.', 'This is my new phone.'] },
      { id: 'jiu_old', zh: '旧', py: 'jiù', en: 'old (things)', ex: ['我的电脑很旧。', 'Wǒ de diànnǎo hěn jiù.', 'My computer is old.'], note: '旧 is for things. Old people are 老 lǎo.' },
      { id: 'haokan', zh: '好看', py: 'hǎokàn', en: 'good-looking / nice', ex: ['这件衣服很好看。', 'Zhè jiàn yīfu hěn hǎokàn.', 'This top looks great.'], note: '件 is the measure word for clothes (for the top half).', lit: 'good (to) look (at)' },
      { id: 'kuai_fast', zh: '快', py: 'kuài', en: 'fast', ex: ['他说得太快了。', 'Tā shuō de tài kuài le.', 'He speaks too fast.'], note: 'Verb + 得 + how: 说得快 speaks fast, 说得很好 speaks well. 得 is de here.' },
      { id: 'man', zh: '慢', py: 'màn', en: 'slow', ex: ['这个电脑太慢了。', 'Zhège diànnǎo tài màn le.', 'This computer is too slow.'] },
      { id: 'gao', zh: '高', py: 'gāo', en: 'tall / high', ex: ['你哥哥很高。', 'Nǐ gēge hěn gāo.', 'Your brother is tall.'] },
      { id: 'bi', zh: '比', py: 'bǐ', en: 'than (comparing)', ex: ['他比我高。', 'Tā bǐ wǒ gāo.', 'He\'s taller than me.'], note: 'A 比 B + adjective, with no 很: 他比我高, not 他比我很高.' },
    ],
  },
  {
    id: 'u24', title: 'Linking ideas', emoji: '🔗',
    items: [
      { id: 'yinwei', zh: '因为', py: 'yīnwèi', en: 'because', ex: ['因为下雨，我不去了。', 'Yīnwèi xià yǔ, wǒ bú qù le.', 'Because it\'s raining, I\'m not going.'], note: '因为 … 所以 … (because … so …) often go together: 因为很累，所以我睡觉了.' },
      { id: 'suoyi', zh: '所以', py: 'suǒyǐ', en: 'so / therefore', ex: ['我很累，所以早点睡。', 'Wǒ hěn lèi, suǒyǐ zǎo diǎn shuì.', 'I\'m tired, so I\'ll go to bed early.'] },
      { id: 'danshi', zh: '但是', py: 'dànshì', en: 'but', ex: ['中文很难，但是很有意思。', 'Zhōngwén hěn nán, dànshì hěn yǒu yìsi.', 'Chinese is hard, but it\'s really interesting.'] },
      { id: 'haishi', zh: '还是', py: 'háishi', en: 'or (in questions)', ex: ['你喝茶还是咖啡？', 'Nǐ hē chá háishi kāfēi?', 'Would you like tea or coffee?'], note: 'In a question "or" is 还是. In a statement it\'s 或者 huòzhě.' },
      { id: 'huozhe', zh: '或者', py: 'huòzhě', en: 'or (in statements)', ex: ['明天或者后天都可以。', 'Míngtiān huòzhě hòutiān dōu kěyǐ.', 'Tomorrow or the day after, either is fine.'] },
      { id: 'ye', zh: '也', py: 'yě', en: 'also / too', ex: ['我也是！', 'Wǒ yě shì!', 'Me too!'], note: '也 goes before the verb, never at the end: 我也喜欢 "I like it too".' },
      { id: 'dou', zh: '我们都去', py: 'wǒmen dōu qù', en: 'we\'re all going', ex: ['我们都是学生。', 'Wǒmen dōu shì xuésheng.', 'We\'re all students.'], note: '都 (all, both) also goes before the verb, after the people or things it covers.' },
      { id: 'keneng', zh: '可能', py: 'kěnéng', en: 'maybe / probably', ex: ['他可能不来了。', 'Tā kěnéng bù lái le.', 'He\'s probably not coming.'] },
      { id: 'qishi', zh: '其实', py: 'qíshí', en: 'actually', ex: ['其实我不喜欢咖啡。', 'Qíshí wǒ bù xǐhuan kāfēi.', 'Actually, I don\'t like coffee.'] },
      { id: 'na', zh: '那好吧', py: 'nà hǎo ba', en: 'well, OK then', ex: ['你不来？那好吧。', 'Nǐ bù lái? Nà hǎo ba.', 'You\'re not coming? Well, OK then.'], note: 'At the start of a sentence, 那 means "well then" or "in that case": 那我们走吧 "well then, let\'s go".' },
      { id: 'ruguo', zh: '如果', py: 'rúguǒ', en: 'if', ex: ['如果明天下雨，我们就不去了。', 'Rúguǒ míngtiān xià yǔ, wǒmen jiù bú qù le.', 'If it rains tomorrow, we won\'t go.'], note: '如果 … 就 …: if … then …. 就 goes before the verb in the second half.' },
    ],
  },
  {
    id: 'u25', title: 'Dates & ages', emoji: '🎂',
    items: [
      { id: 'jihao', zh: '几号？', py: 'jǐ hào?', en: 'what\'s the date?', ex: ['今天几号？——十五号。', 'Jīntiān jǐ hào? — Shíwǔ hào.', 'What\'s the date today? — The fifteenth.'], note: '号 is the day of the month in everyday speech.' },
      { id: 'yue', zh: '月', py: 'yuè', en: 'month', ex: ['我三月去中国。', 'Wǒ sān yuè qù Zhōngguó.', 'I\'m going to China in March.'], note: 'Months are just a number + 月: 一月 January … 十二月 December.' },
      { id: 'shengri', zh: '生日', py: 'shēngrì', en: 'birthday', ex: ['你的生日是几月几号？', 'Nǐ de shēngrì shì jǐ yuè jǐ hào?', 'When\'s your birthday?'], lit: 'born day' },
      { id: 'shengrikuaile', zh: '生日快乐', py: 'shēngrì kuàilè', en: 'happy birthday', ex: ['祝你生日快乐！', 'Zhù nǐ shēngrì kuàilè!', 'Happy birthday to you!'], lit: 'birthday happy' },
      { id: 'duoda', zh: '你多大？', py: 'nǐ duō dà?', en: 'how old are you?', ex: ['你今年多大？——二十五岁。', 'Nǐ jīnnián duō dà? — Èrshíwǔ suì.', 'How old are you? — Twenty-five.'], note: 'Ask a child 几岁 jǐ suì, an adult 多大, and an older person 多大年纪 duō dà niánjì.', lit: 'you how big?' },
      { id: 'sui', zh: '岁', py: 'suì', en: 'years old', ex: ['我女儿三岁。', 'Wǒ nǚ\'ér sān suì.', 'My daughter is three.'], note: 'No 是 with ages: 我二十岁 "I\'m twenty".' },
      { id: 'jinnian', zh: '今年', py: 'jīnnián', en: 'this year', ex: ['今年我想去中国。', 'Jīnnián wǒ xiǎng qù Zhōngguó.', 'This year I want to go to China.'] },
      { id: 'houtian', zh: '后天', py: 'hòutiān', en: 'the day after tomorrow', ex: ['后天是星期六。', 'Hòutiān shì xīngqī liù.', 'The day after tomorrow is Saturday.'], lit: 'after day' },
      { id: 'qiantian', zh: '前天', py: 'qiántiān', en: 'the day before yesterday', ex: ['前天我去看电影了。', 'Qiántiān wǒ qù kàn diànyǐng le.', 'I went to see a movie the day before yesterday.'], lit: 'before day' },
      { id: 'shangwu', zh: '上午', py: 'shàngwǔ', en: 'morning (before noon)', ex: ['我上午有课。', 'Wǒ shàngwǔ yǒu kè.', 'I have class in the morning.'] },
      { id: 'xiawu', zh: '下午', py: 'xiàwǔ', en: 'afternoon', ex: ['下午三点见。', 'Xiàwǔ sān diǎn jiàn.', 'See you at three this afternoon.'] },
    ],
  },
  {
    id: 'u26', title: 'Family & pets', emoji: '🐶',
    items: [
      { id: 'didi', zh: '弟弟', py: 'dìdi', en: 'younger brother', ex: ['我弟弟在上大学。', 'Wǒ dìdi zài shàng dàxué.', 'My younger brother is at university.'] },
      { id: 'meimei', zh: '妹妹', py: 'mèimei', en: 'younger sister', ex: ['我有两个妹妹。', 'Wǒ yǒu liǎng ge mèimei.', 'I have two younger sisters.'] },
      { id: 'haizi', zh: '孩子', py: 'háizi', en: 'child', ex: ['你有孩子吗？', 'Nǐ yǒu háizi ma?', 'Do you have children?'] },
      { id: 'erzi', zh: '儿子', py: 'érzi', en: 'son', ex: ['他儿子很聪明。', 'Tā érzi hěn cōngming.', 'His son is very clever.'] },
      { id: 'nver', zh: '女儿', py: 'nǚ\'ér', en: 'daughter', ex: ['她女儿很可爱。', 'Tā nǚ\'ér hěn kě\'ài.', 'Her daughter is very cute.'] },
      { id: 'laogong', zh: '老公', py: 'lǎogōng', en: 'husband', ex: ['这是我老公。', 'Zhè shì wǒ lǎogōng.', 'This is my husband.'], note: '老公 and 老婆 are the everyday words for husband and wife. 丈夫 and 妻子 are more formal.' },
      { id: 'laopo', zh: '老婆', py: 'lǎopo', en: 'wife', ex: ['我老婆是医生。', 'Wǒ lǎopo shì yīshēng.', 'My wife is a doctor.'] },
      { id: 'jiehun', zh: '结婚', py: 'jiéhūn', en: 'to get married', ex: ['你结婚了吗？', 'Nǐ jiéhūn le ma?', 'Are you married?'] },
      { id: 'jiaren', zh: '家人', py: 'jiārén', en: 'family (members)', ex: ['我很想我的家人。', 'Wǒ hěn xiǎng wǒ de jiārén.', 'I really miss my family.'], note: '想 + a person means to miss them.' },
      { id: 'chongwu', zh: '宠物', py: 'chǒngwù', en: 'pet', ex: ['你有宠物吗？——我有一只猫。', 'Nǐ yǒu chǒngwù ma? — Wǒ yǒu yì zhī māo.', 'Do you have a pet? — I have a cat.'], note: '只 zhī is the measure word for most animals: 一只猫, 两只狗.' },
      { id: 'keai', zh: '可爱', py: 'kě\'ài', en: 'cute', ex: ['你的狗真可爱！', 'Nǐ de gǒu zhēn kě\'ài!', 'Your dog is so cute!'] },
    ],
  },
];

// Syllables with one common character per tone, for the tone trainer.
// Tone numbers index the chars array: [tone1, tone2, tone3, tone4]. Each character has only one
// reading, since its clip is made from the character alone.
export const TONE_SETS = [
  { base: 'ma', py: ['mā', 'má', 'mǎ', 'mà'], zh: ['妈', '麻', '马', '骂'] },
  { base: 'yi', py: ['yī', 'yí', 'yǐ', 'yì'], zh: ['衣', '姨', '椅', '亿'] },
  { base: 'ba', py: ['bā', 'bá', 'bǎ', 'bà'], zh: ['八', '拔', '把', '爸'] },
  { base: 'tang', py: ['tāng', 'táng', 'tǎng', 'tàng'], zh: ['汤', '糖', '躺', '烫'] },
  { base: 'shi', py: ['shī', 'shí', 'shǐ', 'shì'], zh: ['诗', '十', '使', '是'] },
  { base: 'guo', py: ['guō', 'guó', 'guǒ', 'guò'], zh: ['锅', '国', '果', '过'] },
  { base: 'tu', py: ['tū', 'tú', 'tǔ', 'tù'], zh: ['秃', '图', '土', '兔'] },
  { base: 'fan', py: ['fān', 'fán', 'fǎn', 'fàn'], zh: ['翻', '烦', '反', '饭'] },
  { base: 'mi', py: ['mī', 'mí', 'mǐ', 'mì'], zh: ['眯', '迷', '米', '蜜'] },
  { base: 'qi', py: ['qī', 'qí', 'qǐ', 'qì'], zh: ['七', '骑', '起', '气'] },
  { base: 'wen', py: ['wēn', 'wén', 'wěn', 'wèn'], zh: ['温', '文', '稳', '问'] },
  { base: 'bi', py: ['bī', 'bí', 'bǐ', 'bì'], zh: ['逼', '鼻', '笔', '必'] },
  { base: 'da', py: ['dā', 'dá', 'dǎ', 'dà'], zh: ['搭', '达', '打', '大'] },
  { base: 'hu', py: ['hū', 'hú', 'hǔ', 'hù'], zh: ['呼', '湖', '虎', '户'] },
  { base: 'xi', py: ['xī', 'xí', 'xǐ', 'xì'], zh: ['西', '习', '洗', '细'] },
  { base: 'ji', py: ['jī', 'jí', 'jǐ', 'jì'], zh: ['鸡', '急', '挤', '记'] },
  { base: 'fu', py: ['fū', 'fú', 'fǔ', 'fù'], zh: ['肤', '服', '府', '父'] },
  { base: 'yu', py: ['yū', 'yú', 'yǔ', 'yù'], zh: ['迂', '鱼', '雨', '玉'] },
  { base: 'wu', py: ['wū', 'wú', 'wǔ', 'wù'], zh: ['屋', '无', '五', '雾'] },
  { base: 'zhu', py: ['zhū', 'zhú', 'zhǔ', 'zhù'], zh: ['猪', '竹', '煮', '住'] },
  { base: 'chu', py: ['chū', 'chú', 'chǔ', 'chù'], zh: ['出', '厨', '楚', '触'] },
  { base: 'mao', py: ['māo', 'máo', 'mǎo', 'mào'], zh: ['猫', '毛', '卯', '帽'] },
  { base: 'qian', py: ['qiān', 'qián', 'qiǎn', 'qiàn'], zh: ['千', '钱', '浅', '欠'] },
  { base: 'yan', py: ['yān', 'yán', 'yǎn', 'yàn'], zh: ['烟', '盐', '眼', '验'] },
  { base: 'yang', py: ['yāng', 'yáng', 'yǎng', 'yàng'], zh: ['央', '羊', '养', '样'] },
  { base: 'tao', py: ['tāo', 'táo', 'tǎo', 'tào'], zh: ['掏', '桃', '讨', '套'] },
  { base: 'xiang', py: ['xiāng', 'xiáng', 'xiǎng', 'xiàng'], zh: ['香', '详', '想', '象'] },
  { base: 'qing', py: ['qīng', 'qíng', 'qǐng', 'qìng'], zh: ['青', '晴', '请', '庆'] },
  { base: 'ying', py: ['yīng', 'yíng', 'yǐng', 'yìng'], zh: ['英', '赢', '影', '硬'] },
  { base: 'zhi', py: ['zhī', 'zhí', 'zhǐ', 'zhì'], zh: ['知', '直', '纸', '志'] },
  { base: 'chi', py: ['chī', 'chí', 'chǐ', 'chì'], zh: ['吃', '迟', '尺', '翅'] },
  { base: 'hui', py: ['huī', 'huí', 'huǐ', 'huì'], zh: ['灰', '回', '毁', '汇'] },
  { base: 'you', py: ['yōu', 'yóu', 'yǒu', 'yòu'], zh: ['优', '油', '有', '右'] },
  { base: 'lao', py: ['lāo', 'láo', 'lǎo', 'lào'], zh: ['捞', '劳', '老', '涝'] },
  { base: 'chuan', py: ['chuān', 'chuán', 'chuǎn', 'chuàn'], zh: ['穿', '船', '喘', '串'] },
  { base: 'tong', py: ['tōng', 'tóng', 'tǒng', 'tòng'], zh: ['通', '同', '桶', '痛'] },
  { base: 'jie', py: ['jiē', 'jié', 'jiě', 'jiè'], zh: ['街', '节', '姐', '借'] },
  { base: 'xian', py: ['xiān', 'xián', 'xiǎn', 'xiàn'], zh: ['先', '咸', '险', '线'] },
  { base: 'tui', py: ['tuī', 'tuí', 'tuǐ', 'tuì'], zh: ['推', '颓', '腿', '退'] },
  { base: 'xiao', py: ['xiāo', 'xiáo', 'xiǎo', 'xiào'], zh: ['消', '淆', '小', '笑'] },
  { base: 'wan', py: ['wān', 'wán', 'wǎn', 'wàn'], zh: ['弯', '完', '晚', '万'] },
  { base: 'huan', py: ['huān', 'huán', 'huǎn', 'huàn'], zh: ['欢', '环', '缓', '换'] },
  { base: 'ya', py: ['yā', 'yá', 'yǎ', 'yà'], zh: ['鸭', '牙', '雅', '亚'] },
  { base: 'yao', py: ['yāo', 'yáo', 'yǎo', 'yào'], zh: ['腰', '摇', '咬', '药'] },
];

export const TONE_INFO = [
  { n: 1, name: '1st tone', shape: 'high & flat', tip: 'Hold one high note, like singing "laaa".', path: [[0, 5], [1, 5]] },
  { n: 2, name: '2nd tone', shape: 'rising', tip: 'Rise like asking "Huh?"', path: [[0, 3], [1, 5]] },
  { n: 3, name: '3rd tone', shape: 'low (dip)', tip: 'Dip low, then come back up. (Inside words it usually just stays low.)', path: [[0, 2], [0.5, 1], [1, 3.5]] },
  { n: 4, name: '4th tone', shape: 'falling', tip: 'Drop sharply, like a firm "No!"', path: [[0, 5], [1, 1]] },
];

// Real two-syllable words for the tone-pair stage: 3 per tone combination.
// 3–3 words are left out on purpose: they're spoken 2–3 (tone sandhi), which is taught later with phrases.
export const PAIR_WORDS = [
  ['飞机', 'fēijī', 'airplane'], ['咖啡', 'kāfēi', 'coffee'], ['今天', 'jīntiān', 'today'],
  ['中国', 'Zhōngguó', 'China'], ['欢迎', 'huānyíng', 'welcome'], ['公园', 'gōngyuán', 'park'],
  ['身体', 'shēntǐ', 'body'], ['铅笔', 'qiānbǐ', 'pencil'], ['开始', 'kāishǐ', 'to begin'],
  ['医院', 'yīyuàn', 'hospital'], ['音乐', 'yīnyuè', 'music'], ['高兴', 'gāoxìng', 'happy'],
  ['明天', 'míngtiān', 'tomorrow'], ['房间', 'fángjiān', 'room'], ['国家', 'guójiā', 'country'],
  ['学习', 'xuéxí', 'to study'], ['银行', 'yínháng', 'bank'], ['同学', 'tóngxué', 'classmate'],
  ['苹果', 'píngguǒ', 'apple'], ['没有', 'méiyǒu', 'not have'], ['游泳', 'yóuyǒng', 'to swim'],
  ['学校', 'xuéxiào', 'school'], ['同事', 'tóngshì', 'colleague'], ['迟到', 'chídào', 'to be late'],
  ['老师', 'lǎoshī', 'teacher'], ['北京', 'Běijīng', 'Beijing'], ['手机', 'shǒujī', 'mobile phone'],
  ['美国', 'Měiguó', 'USA'], ['旅行', 'lǚxíng', 'to travel'], ['可能', 'kěnéng', 'maybe'],
  ['考试', 'kǎoshì', 'exam'], ['马上', 'mǎshàng', 'right away'], ['米饭', 'mǐfàn', 'rice'],
  ['面包', 'miànbāo', 'bread'], ['上班', 'shàngbān', 'to go to work'], ['汽车', 'qìchē', 'car'],
  ['问题', 'wèntí', 'question'], ['大学', 'dàxué', 'university'], ['练习', 'liànxí', 'to practise'],
  ['电脑', 'diànnǎo', 'computer'], ['汉语', 'Hànyǔ', 'Chinese language'], ['跳舞', 'tiàowǔ', 'to dance'],
  ['再见', 'zàijiàn', 'goodbye'], ['电视', 'diànshì', 'TV'], ['睡觉', 'shuìjiào', 'to sleep'],
].map(([zh, py, en]) => ({ zh, py, en }));

// Words where what you hear differs from the dictionary tones, for the tone-changes stage.
// [zh, written pinyin, spoken pinyin (only when it differs), en]. Unmarked syllables are neutral tone.
export const CHANGE_WORDS = [
  // Neutral tone: the second syllable is short and light, its pitch set by the tone before it.
  ['妈妈', 'māma', null, 'mom'], ['哥哥', 'gēge', null, 'older brother'], ['东西', 'dōngxi', null, 'thing'],
  ['衣服', 'yīfu', null, 'clothes'], ['先生', 'xiānsheng', null, 'Mr. / sir'], ['他们', 'tāmen', null, 'they'],
  ['朋友', 'péngyou', null, 'friend'], ['名字', 'míngzi', null, 'name'], ['孩子', 'háizi', null, 'child'],
  ['什么', 'shénme', null, 'what'], ['便宜', 'piányi', null, 'cheap'], ['石头', 'shítou', null, 'stone'],
  ['姐姐', 'jiějie', null, 'older sister'], ['喜欢', 'xǐhuan', null, 'to like'], ['我们', 'wǒmen', null, 'we'],
  ['椅子', 'yǐzi', null, 'chair'], ['耳朵', 'ěrduo', null, 'ear'], ['奶奶', 'nǎinai', null, 'grandma'],
  ['爸爸', 'bàba', null, 'dad'], ['谢谢', 'xièxie', null, 'thank you'], ['意思', 'yìsi', null, 'meaning'],
  ['漂亮', 'piàoliang', null, 'pretty'], ['弟弟', 'dìdi', null, 'younger brother'], ['看看', 'kànkan', null, 'have a look'],
  // Two 3rd tones: the first one is said as a 2nd tone.
  ['你好', 'nǐ hǎo', 'ní hǎo', 'hello'], ['很好', 'hěn hǎo', 'hén hǎo', 'very good'], ['可以', 'kěyǐ', 'kéyǐ', 'can / may'],
  ['水果', 'shuǐguǒ', 'shuíguǒ', 'fruit'], ['老虎', 'lǎohǔ', 'láohǔ', 'tiger'], ['小姐', 'xiǎojiě', 'xiáojiě', 'Miss'],
  ['洗澡', 'xǐzǎo', 'xízǎo', 'to shower'], ['手表', 'shǒubiǎo', 'shóubiǎo', 'watch'], ['雨伞', 'yǔsǎn', 'yúsǎn', 'umbrella'],
  ['所以', 'suǒyǐ', 'suóyǐ', 'so / therefore'], ['口语', 'kǒuyǔ', 'kóuyǔ', 'spoken language'], ['很远', 'hěn yuǎn', 'hén yuǎn', 'very far'],
  // 不 (bù) becomes bú before a 4th tone, and stays bù otherwise.
  ['不是', 'bù shì', 'bú shì', 'is not'], ['不对', 'bù duì', 'bú duì', 'not right'], ['不要', 'bù yào', 'bú yào', 'don\'t want'],
  ['不去', 'bù qù', 'bú qù', 'not go'], ['不好', 'bù hǎo', null, 'not good'], ['不来', 'bù lái', null, 'not come'],
  ['不喝', 'bù hē', null, 'not drink'], ['不忙', 'bù máng', null, 'not busy'],
  // 一 (yī) becomes yí before a 4th tone and yì before tones 1–3.
  ['一样', 'yīyàng', 'yíyàng', 'the same'], ['一定', 'yīdìng', 'yídìng', 'definitely'], ['一半', 'yībàn', 'yíbàn', 'half'],
  ['一起', 'yīqǐ', 'yìqǐ', 'together'], ['一天', 'yī tiān', 'yì tiān', 'one day'], ['一年', 'yī nián', 'yì nián', 'one year'],
].map(([zh, py, said, en]) => ({ zh, py, said: said || py, en }));

// Sounds English speakers mix up. Each group differs in one sound only and shares a tone,
// so the only thing to listen for is the contrast itself.
export const SOUND_SETS = [
  { id: 'zh-j-z', label: 'zh · j · z', tip: 'zh: tongue tip curled back. j: tongue flat behind the lower teeth, lips spread. z: like the "ds" in "kids".',
    groups: [[['知', 'zhī'], ['鸡', 'jī'], ['资', 'zī']], [['找', 'zhǎo'], ['早', 'zǎo']], [['战', 'zhàn'], ['赞', 'zàn']]] },
  { id: 'ch-q-c', label: 'ch · q · c', tip: 'Same tongue positions as zh · j · z, plus a strong puff of air. c sounds like the "ts" in "cats".',
    groups: [[['吃', 'chī'], ['七', 'qī'], ['疵', 'cī']], [['炒', 'chǎo'], ['草', 'cǎo']], [['春', 'chūn'], ['村', 'cūn']]] },
  { id: 'sh-x-s', label: 'sh · x · s', tip: 'sh: tongue curled back. x: tongue flat, lips spread, between "see" and "she". s: like English s.',
    groups: [[['诗', 'shī'], ['西', 'xī'], ['丝', 'sī']], [['山', 'shān'], ['三', 'sān']], [['是', 'shì'], ['四', 'sì']], [['少', 'shǎo'], ['小', 'xiǎo'], ['扫', 'sǎo']]] },
  { id: 'u-v', label: 'u · ü', tip: 'ü: say "ee", then round your lips without moving your tongue. u is like "oo".',
    groups: [[['路', 'lù'], ['绿', 'lǜ']], [['努', 'nǔ'], ['女', 'nǚ']], [['无', 'wú'], ['鱼', 'yú']]] },
  { id: 'n-ng', label: '-n · -ng', tip: '-n ends with the tongue tip touching behind the teeth. -ng ends at the back of the mouth, like "sing".',
    groups: [[['饭', 'fàn'], ['放', 'fàng']], [['班', 'bān'], ['帮', 'bāng']], [['心', 'xīn'], ['星', 'xīng']], [['亲', 'qīn'], ['青', 'qīng']], [['盆', 'pén'], ['朋', 'péng']], [['人', 'rén'], ['仍', 'réng']]] },
  { id: 'r-l', label: 'r · l', tip: 'Chinese r is close to the "s" in "pleasure", said with the tongue curled back. l is like English l.',
    groups: [[['日', 'rì'], ['力', 'lì']], [['入', 'rù'], ['路', 'lù']], [['让', 'ràng'], ['浪', 'làng']], [['肉', 'ròu'], ['漏', 'lòu']]] },
  { id: 'air', label: 'b/p · d/t · g/k', tip: 'p, t, k, c, ch, q have a strong puff of air (hold a hand in front of your mouth). b, d, g, z, zh, j have none.',
    groups: [[['爸', 'bà'], ['怕', 'pà']], [['大', 'dà'], ['踏', 'tà']], [['个', 'gè'], ['课', 'kè']], [['在', 'zài'], ['菜', 'cài']], [['纸', 'zhǐ'], ['尺', 'chǐ']], [['多', 'duō'], ['拖', 'tuō']]] },
];
